// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzku4Z39lLzURdxKXw4a_bAt1cwoFMXgk',
    appId: '1:222586627793:web:a909d90f81977c302287f0',
    messagingSenderId: '222586627793',
    projectId: 'ppks-gallery-reservation',
    authDomain: 'ppks-gallery-reservation.firebaseapp.com',
    storageBucket: 'ppks-gallery-reservation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJPKOw4F-0TxwgpUZSj1VR_Qsl0nG6h0',
    appId: '1:222586627793:android:3d008dc2602fa6a02287f0',
    messagingSenderId: '222586627793',
    projectId: 'ppks-gallery-reservation',
    storageBucket: 'ppks-gallery-reservation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxZdamSJCJe3HzdxB1Xy51NXrqQVvG0DA',
    appId: '1:222586627793:ios:247cc1bb992541642287f0',
    messagingSenderId: '222586627793',
    projectId: 'ppks-gallery-reservation',
    storageBucket: 'ppks-gallery-reservation.firebasestorage.app',
    iosBundleId: 'com.example.projectPpks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxZdamSJCJe3HzdxB1Xy51NXrqQVvG0DA',
    appId: '1:222586627793:ios:247cc1bb992541642287f0',
    messagingSenderId: '222586627793',
    projectId: 'ppks-gallery-reservation',
    storageBucket: 'ppks-gallery-reservation.firebasestorage.app',
    iosBundleId: 'com.example.projectPpks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzku4Z39lLzURdxKXw4a_bAt1cwoFMXgk',
    appId: '1:222586627793:web:cd1d1588b58f6cbe2287f0',
    messagingSenderId: '222586627793',
    projectId: 'ppks-gallery-reservation',
    authDomain: 'ppks-gallery-reservation.firebaseapp.com',
    storageBucket: 'ppks-gallery-reservation.firebasestorage.app',
  );
}
